export const INSTRUMENT_TYPES = [
	"Cymatics - Orchid/pluck/Starlight(C).wav",
	"Cymatics - Orchid/pluck/Water(C).wav",
	"Cymatics - Orchid/bass/Reaper(C).wav",
	"Cymatics - Orchid/bass/PerfectDonk(C).wav",
	"Cymatics - Orchid/keys/Classic(C).wav",
	"Cymatics - Orchid/keys/Swirl(C).wav",
	"Cymatics - Orchid/808/Short(C).wav",
	"Cymatics - Orchid/808/Rum(C).wav",
	"Cymatics - Trap/hihat/Blitz.wav",
	"Cymatics - Trap/hihat/Yellow.wav",
	"Cymatics - Trap/hihat/Turbo.wav",
	"Cymatics - Trap/hihat/Classic.wav",
	"Cymatics - Trap/hihat/French.wav",
	"Cymatics - Trap/hihat/TinyTick.wav",
	"Cymatics - Trap/hihat/Low.wav",
	"Cymatics - Trap/hihat/OuttaHere.wav",
	"Cymatics - Trap/hihat/Drill.wav",
	"Cymatics - Trap/hihat/Halftime.wav",
	"Cymatics - Trap/hihat/Vintage.wav",
	"Cymatics - Trap/hihat/Reverse.wav",
	"Cymatics - Trap/vocals/Chihuahua.wav",
	"Cymatics - Trap/vocals/Explosion.wav",
	"Cymatics - Trap/rimshot/Sigma.wav",
	"Cymatics - Trap/rimshot/Diamonds.wav",
	"Cymatics - Trap/rimshot/Sword.wav",
	"Cymatics - Trap/clap/Future(Gs).wav",
] as const;
export const VOLUME_MAX = 12;
export const VOLUME_MIN = -24;
